#
# Created Makefile the 18:21:14 (19/04/2003) on ro10box
# Last Modification at 00:15:41 (20/04/2003) on ro10box
#
# Contact: rolphin@games-expert.com
#

elftrunc: elftrunc.c
	$(DIET) -c $? -o $@
	./$@ $@ $@
